apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-web
  name: nginx-web
spec:
  replicas: 3
  selector:
    matchLabels:
     app: nginx-web
  strategy:
     type: Recreate
  template:
    metadata:
      labels:
        app: nginx-web
    spec:
     containers:
     - image: nginx:1.16.0
       name: nginx
       resources:
        limits:
          cpu: 0.7
          memory: 128Mi
        requests:
         cpu: 0.5
         memory: 64Mi
